import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import { build } from "esbuild"
import type { BuildOptions } from "esbuild"
import { BUNDLE, BUNDLE_DIR } from "../src/bundle.ts"

const STAMP = "versions.json"
const NOTICES = "THIRD-PARTY-NOTICES.md"
const LICENCE_FILE = /^(?:licen[cs]e|copying)(?:\.\w+)?$/i
const root = fileURLToPath(new URL("..", import.meta.url))
const repo = fileURLToPath(new URL("../../../", import.meta.url))

// The browser condition is what keeps a Bundle file free of Node: it picks the build a package wrote for a runtime
// with no `process` and no `require`, which is what the QuickJS tier is.
const OPTIONS = {
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  external: ["node:*"],
  // eof, not linked: a Bundle file is read as text and evaluated by the QuickJS tier, which can open no sidecar,
  // so the only notice that travels with the copy is one inside the file.
  legalComments: "eof",
} satisfies BuildOptions

interface Stamp {
  options: typeof OPTIONS
  packages: Record<string, { version: string; bytes: number }>
}

const pinned = await versions()

if (!(await fresh())) {
  await rm(BUNDLE_DIR, { recursive: true, force: true })
  await mkdir(BUNDLE_DIR, { recursive: true })
  const packages: Stamp["packages"] = {}
  for (const name of BUNDLE) {
    await build({ ...OPTIONS, entryPoints: [name], absWorkingDir: root, outfile: built(name) })
    packages[name] = { version: pinned[name] ?? "missing", bytes: (await stat(built(name))).size }
  }
  await assertNoBuiltins()
  await writeFile(`${BUNDLE_DIR}${STAMP}`, `${JSON.stringify({ options: OPTIONS, packages }, null, 2)}\n`)
}

const notices = await noticesFile()
await writeFile(`${root}${NOTICES}`, notices)
await writeFile(`${repo}${NOTICES}`, notices)

function built(name: string): string {
  return `${BUNDLE_DIR}${name}.mjs`
}

async function versions(): Promise<Record<string, string>> {
  const manifest = JSON.parse(await readFile(`${root}package.json`, "utf8")) as { dependencies: Record<string, string> }
  return Object.fromEntries(BUNDLE.map((name) => [name, manifest.dependencies[name] ?? "missing"]))
}

// The stamp carries the pinned version and the built size of every Bundle package beside the build's own options,
// so moving a version, changing how the build runs, or losing half a file all rebuild the lot.
async function fresh(): Promise<boolean> {
  const written = await readFile(`${BUNDLE_DIR}${STAMP}`, "utf8").catch(() => undefined)
  if (written === undefined) return false
  let stamp: Stamp
  try {
    stamp = JSON.parse(written) as Stamp
  } catch {
    return false
  }
  if (JSON.stringify(stamp.options) !== JSON.stringify(OPTIONS)) return false
  for (const name of BUNDLE) {
    const entry = stamp.packages?.[name]
    if (entry === undefined || entry.version !== pinned[name]) return false
    const size = await stat(built(name)).then((one) => one.size, () => -1)
    if (size !== entry.bytes) return false
  }
  return true
}

// The Node tier child may import a Bundle file and nothing else, so a Bundle file may import nothing at all.
async function assertNoBuiltins(): Promise<void> {
  for (const name of BUNDLE) {
    const text = await readFile(built(name), "utf8")
    const found = /^\s*(?:import|export)[^\n]*["']node:[a-z_/]+["']/m.exec(text)
    if (found !== null) throw new Error(`${name} bundles to a file that imports ${found[0].trim()}, which no tier serves.`)
  }
}

// esbuild inlines each package's source into its Bundle file, so flintd distributes a copy of all eight and MIT and ISC
// both oblige the copyright line and the permission notice to travel with it.
async function noticesFile(): Promise<string> {
  const sections: string[] = []
  for (const name of BUNDLE) {
    const dir = `${root}node_modules/${name}/`
    const manifest = JSON.parse(await readFile(`${dir}package.json`, "utf8")) as { license?: string }
    const version = pinned[name]
    if (manifest.license === undefined || version === undefined || version === "missing") {
      throw new Error(`${name} has no pinned version or no license field, so ${NOTICES} cannot name what it reproduces.`)
    }
    const text = await licenceText(name, dir)
    sections.push(`## ${name} ${version}\n\nSPDX-License-Identifier: ${manifest.license}\n\n\`\`\`\n${text}\n\`\`\`\n`)
  }
  return `# Third-party notices\n\nflintd itself is Apache-2.0. The eight packages below are compiled into \`@flintd/core\`'s Bundle files\n(\`dist/bundle/*.mjs\`), so a copy of each is distributed with flintd and its licence travels here.\n\nGenerated by \`packages/core/scripts/build-bundle.ts\`. Do not edit by hand.\n\n${sections.join("\n")}`
}

async function licenceText(name: string, dir: string): Promise<string> {
  const found = (await readdir(dir)).filter((entry) => LICENCE_FILE.test(entry)).sort()
  for (const entry of found) {
    const text = (await readFile(`${dir}${entry}`, "utf8")).trim()
    if (text.length > 0) return text
  }
  throw new Error(`${name} ships no licence text in ${dir}, so ${NOTICES} would omit it. Vendor no package whose licence cannot be reproduced.`)
}
